## The pair of functions will cached the inverse of an invertible matrix within
## a special matrix. To use the functions, create a invertible matrix m using
## matrix(). Once it is created, create the special matrix using
## makeCacheMatrix(m) and named it as x. To solve the inverse of the matrix,
## run cacheSolve(x). For the first time, it will compute the inverse and store
## the value in the cache. For second time and onwards, assuming the matrix
## has not been changed, it will simply use the cached inverse instead of
## re-computing the inverse. If the matrix is changed, it will re-compute and
## cache the new inverse value

## makeCacheMatrix will create a special matrix that will allow cacheSolve()
## to store and retrieve the cached inverse value. This function should be
## executed first to obtain the special matrix which will be used by
## cacheSolve()

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinverse <- function(inv) i <<- inv
        getinverse <- function() i
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## cacheSolve will see if there is a cached inverse value in the special
## matrix generated by makeCacheMatrix(). If there is, it will print out the
## cached inverse matrix with the message "getting cached data". If the cache
## is empty or NULL, it will compute the inverse of the matrix and store it
## in the special matrix

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        i <- x$getinverse()
        if (!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setinverse(i)
        i
}
